version: '3'
services:
  demoapp:
    hostname: frontend
    image: dtdemos/casdemoapp:1.0.0
    ports:
      - 80:8080
    environment:
      - DT_CUSTOM_PROP=keptn_project=demo keptn_stage=production keptn_service=casdemoapp
      - DT_RELEASE_PRODUCT=demo
      - DT_RELEASE_STAGE=production
      - DT_RELEASE_VERSION=1.0.0
      - DT_RELEASE_BUILD_VERSION=1.0.0
  sendload:
    hostname: load
    image: dtdemos/casdemoappload:1.0.0
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=80
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
    restart: always