version: '3'
services:
  casdemoapp1:
    hostname: casdemoapp1
    image: dtdemos/casdemoapp:1.0.0
    ports:
      - 80:8080
    environment:
      - DT_CUSTOM_PROP=keptn_project=slo-demo keptn_stage=production keptn_service=casdemoapp
      - DT_RELEASE_PRODUCT=slo-demo
      - DT_RELEASE_STAGE=production
      - DT_RELEASE_VERSION=1.0.0
      - DT_RELEASE_BUILD_VERSION=1.0.0
      - DT_CLUSTER_ID=slo-demo-casdemoapp-production
  casdemoapp2:
    hostname: casdemoapp2
    image: dtdemos/casdemoapp:1.0.0
    ports:
      - 81:8080
    environment:
      - DT_CUSTOM_PROP=keptn_project=incident-demo keptn_stage=production keptn_service=casdemoapp
      - DT_RELEASE_PRODUCT=incident-demo
      - DT_RELEASE_STAGE=production
      - DT_RELEASE_VERSION=1.0.0
      - DT_RELEASE_BUILD_VERSION=1.0.0
      - DT_CLUSTER_ID=incident-demo-casdemoapp-production
  casdemoapp3:
    hostname: casdemoapp3
    image: dtdemos/casdemoapp:1.0.0
    ports:
      - 82:8080
    environment:
      - DT_CUSTOM_PROP=keptn_project=release-demo keptn_stage=staging keptn_service=casdemoapp
      - DT_RELEASE_PRODUCT=release-demo
      - DT_RELEASE_STAGE=staging
      - DT_RELEASE_VERSION=1.0.0
      - DT_RELEASE_BUILD_VERSION=1.0.0
      - DT_CLUSTER_ID=release-demo-casdemoapp-staging
  casdemoapp4:
    hostname: casdemoapp4
    image: dtdemos/casdemoapp:1.0.0
    ports:
      - 83:8080
    environment:
      - DT_CUSTOM_PROP=keptn_project=release-demo keptn_stage=production keptn_service=casdemoapp
      - DT_RELEASE_PRODUCT=release-demo
      - DT_RELEASE_STAGE=production
      - DT_RELEASE_VERSION=1.0.0
      - DT_RELEASE_BUILD_VERSION=1.0.0
      - DT_CLUSTER_ID=release-demo-casdemoapp-production
  casdemoappload1:
    hostname: casdemoappload1
    image: dtdemos/casdemoappload:1.0.0
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=80
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
    restart: always
  casdemoappload2:
    hostname: casdemoappload2
    image: dtdemos/casdemoappload:1.0.0
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=81
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
    restart: always
  casdemoappload3:
    hostname: casdemoappload3
    image: dtdemos/casdemoappload:1.0.0
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=82
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
    restart: always
  casdemoappload4:
    hostname: casdemoappload4
    image: dtdemos/casdemoappload:1.0.0
    environment:
      - HOSTNAME=172.17.0.1
      - SERVER_PORT=83
      - NUM_LOOPS=10000
      - NUM_THREADS=1
      - THINK_TIME=250
      - TEST_SCRIPT=load.jmx
      - TEST_DEBUG=false
    restart: always