apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "shipyard-demo"
spec:
  stages:
    - name: "production"
      sequences:
      - name: "mysequence"
        tasks: 
        - name: "mytask"
